### ISSUE TITLE
Generate and Download button doesn't work or work wrong on Ozon.ru

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn#156]
1. Go to ozon.ru (same behavior on Angular page)
2. Identify controls and press Generate and Download button
Nothing happens.
Here is the output in Dev Console:

Error in event handler: TypeError: Cannot read property 'lastIndexOf' of undefined
    at complexLocators (<URL>)
    at genCodeOfElements (<URL>)
    at pageCode (<URL>)
    at ConversionToCodeModel.genPageCode (<URL>)
    at onXpathGenerated (<URL>)
    at <URL>
panel.html:1 Error in event handler: TypeError: Cannot read property 'lastIndexOf' of undefined
    at complexLocators (chrome-extension://onianeiijhigcmfoljlomccoedikhkei/main.bundle.js:9882:43)
    at genCodeOfElements (chrome-extension://onianeiijhigcmfoljlomccoedikhkei/main.bundle.js:9953:136)
    at pageCode (chrome-extension://onianeiijhigcmfoljlomccoedikhkei/main.bundle.js:10026:55)
    at ConversionToCodeModel.genPageCode (chrome-extension://onianeiijhigcmfoljlomccoedikhkei/main.bundle.js:10043:28)
    at onXpathGenerated (chrome-extension://onianeiijhigcmfoljlomccoedikhkei/main.bundle.js:74305:31)
    at chrome-extension://onianeiijhigcmfoljlomccoedikhkei/main.bundle.js:74311:40

**Comment by AlexeyGirin** [comment]
![image](https://user-images.githubusercontent.com/26869421/120157390-a68ad300-c1fb-11eb-9237-0d1e0c06fda9.png)

**Comment by DaryaGurtovenko** [comment]
On ver. 3.0.8 files can be generated and successfully downloaded
